-- MySQL Script generated by MySQL Workbench
-- Mon May  4 13:53:02 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema loja_ihs_3003
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja_ihs_3003
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja_ihs_3003` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `loja_ihs_3003` ;

-- -----------------------------------------------------
-- Table `loja_ihs_3003`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs_3003`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(100) NULL DEFAULT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs_3003`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs_3003`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `dataCad` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs_3003`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs_3003`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clienteId` INT NOT NULL,
  `cep` VARCHAR(9) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `logradouro` VARCHAR(100) NULL DEFAULT NULL,
  `complemento` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `clienteId` (`clienteId` ASC) VISIBLE,
  CONSTRAINT `enderecos_ibfk_1`
    FOREIGN KEY (`clienteId`)
    REFERENCES `loja_ihs_3003`.`clientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs_3003`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs_3003`.`pedidos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ClienteId` INT NOT NULL,
  `SubTotal` DECIMAL(18,2) NOT NULL,
  `Status` ENUM('Aberto', 'Finalizado', 'Pendente') NOT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`, `ClienteId`),
  INDEX `PK_clientes_pedidos` (`ClienteId` ASC) VISIBLE,
  CONSTRAINT `PK_clientes_pedidos`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `loja_ihs_3003`.`clientes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs_3003`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs_3003`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `caminhoImagem` VARCHAR(255) NOT NULL,
  `dataCad` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `loja_ihs_3003`.`categorias` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs_3003`.`itens_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs_3003`.`itens_pedidos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PedidoId` INT NOT NULL,
  `ProdutoId` INT NOT NULL,
  `Quantidade` DECIMAL(18,2) NOT NULL,
  `ValorItem` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`Id`, `PedidoId`, `ProdutoId`),
  INDEX `FK_itens_pedidos_pedidos` (`PedidoId` ASC) VISIBLE,
  INDEX `FK_itens_pedidos_produtos` (`ProdutoId` ASC) VISIBLE,
  CONSTRAINT `FK_itens_pedidos_pedidos`
    FOREIGN KEY (`PedidoId`)
    REFERENCES `loja_ihs_3003`.`pedidos` (`Id`),
  CONSTRAINT `FK_itens_pedidos_produtos`
    FOREIGN KEY (`ProdutoId`)
    REFERENCES `loja_ihs_3003`.`produtos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs_3003`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs_3003`.`telefones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clienteId` INT NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `clienteId` (`clienteId` ASC) VISIBLE,
  CONSTRAINT `telefones_ibfk_1`
    FOREIGN KEY (`clienteId`)
    REFERENCES `loja_ihs_3003`.`clientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
